### ISSUE TITLE
Sample data location

### ISSUE THREAD

**Issue by NRuben** [mulesoft-labs/data-weave-language-server#26]
Is it possible to specify where the sample data is stored?

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't exist.

**Comment by machaval** [comment]
Not currently. Do you have any suggestion? We could make it configurable.

**Comment by NRuben** [comment]
Well, we wanted to create a repo of useful DataWeave snippets, and this requires a place inside the project to contain the inputs. The easiest solution would be the to change the base path to the project root.
