### ISSUE TITLE
Full screen view of a DW script

### ISSUE THREAD

**Issue by edoschatz** [mulesoft-labs/data-weave-language-server#35]
Greetings to all Mule fans!

As suggested by [Mr. Khan](https://www.linkedin.com/in/amir-khan-ak/) from MuleSoft, I am writing about an idea that came to my mind while talking about the DataWeave plug-in for Visual Studio Code.

There are three buttons on the top right corner of the Transform Message property panel, right next to the Preview button. It would be very helpful if there would be an additional button to full screen the script, so that large scripts would not have to be scrolled horizontally and vertically. If not that, some kind of a button with a task to open a script in an external editor could also be helpful. One thing is for sure - the space imagined for writing DW scripts in Anypoint Studio is absolutely to small. Just imagine some very usual transformation of data from one Salesforce to another where entities have large number of properties and in the same time one can "fit" ten or so lines in that tiny little space.

Keep up the good work!

Best regards to you all!
Edo Schatz

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't exist.

**Comment by afelisatti** [comment]
Hi, @edoschatz. Thanks for the suggestion. We are working on improving the real state of scripts in our future tools. In the meantime, one workaround I have found is to maximize the Studio editor window:
![maximize](https://user-images.githubusercontent.com/3932724/137731180-f82d83de-a375-4ecc-b4ee-17b9db8752ff.gif)

**Comment by edoschatz** [comment]
Hi @afelisatti. The workaround is not bad, at list the maximizing part. When it comes to minimizing, around the minimizing buttons, there are other maximize/minimize buttons, which makes this procedure a little bit less quick to find/click, but it is a good idea though. I will be using it maximized for sure. Thank you for the quick answer and keep up the good work!
