### ISSUE TITLE
Running a test through Visual Studio Code results in a generic error

### ISSUE THREAD

**Issue by pedes** [mulesoft-labs/data-weave-language-server#41]
When defining a hello-world project, with any kind of function and having a test pointing to that function, when we click Run test, the output of the Visual studio code is always the same. (see the screenshot)

Please do provide a guideline or a tested project that works with the current version of the plugin in the Visual Studio Code (July 11th 2022)
Version | 1.2.8 |  
Released on | 09/03/2022, 23:46:03 |  
Last updated | 07/07/2022, 19:30:55

`Error: Unable to resolve reference or to find testing file`

<img width="1591" alt="Screenshot 2022-07-11 at 21 51 36" src="https://user-images.githubusercontent.com/533797/178351005-d38ff64e-e5f2-48a4-ac6b-f8b9d0f0a0dd.png">
<img width="1254" alt="Screenshot 2022-07-11 at 21 51 44" src="https://user-images.githubusercontent.com/533797/178351015-f6f992d4-7dff-46c9-a50a-42c14dc41b17.png">

**Comment by martincousido** [comment]
Hi @pedes This should be fixed now on newest release: 1.2.9.
Please try it out and reopen the issue if needed.
Thank you for the report.
