### ISSUE TITLE
Make tabSize a setting

### ISSUE THREAD

**Issue by AktasC** [mulesoft-labs/data-weave-language-server#42]
- Extension : MuleSoftInc.dataweave  
- Version : latest / `v1.2.10`  
- Environment : Tested on both Visual Studio Code & VSCodium on MacOS Monterey 12.6

Pretty self-explanatory, it would be nice to have the option to change tabs' size when formatting dwl code.   
As of now, it's static and set to 4 per tab, making some nested transformations harder to read.  

Regards.

**Comment by machaval** [comment]
The TabSize that is being used is the same one to any VScode plugin. The property is editor.tabSize if you want to edit the json, but it can also be eddited in the settings GUI. Let me know if it doesn't work for you.
<img width="901" alt="Screen Shot 2022-09-26 at 13 36 19" src="https://user-images.githubusercontent.com/101496/192332758-9ad9073b-2987-42dd-89b6-7d81f012dc47.png">
