### ISSUE TITLE
GitHub Release version is out of sync with the VS Code version

### ISSUE THREAD

**Issue by mohanmmm** [mulesoft-labs/data-weave-language-server#47]
The code version in the GitHub is much older than the extension pack.  Can you please update the GitHub code to match the VS code extension version?
https://github.com/mulesoft-labs/data-weave-language-server
Release v1.1.1
Latest on Sep 16, 2021
https://marketplace.visualstudio.com/items?itemName=MuleSoftInc.dataweave
More Info
Version 1.2.15
Released on 3/9/2022, 2:46:03 PM
Last updated 1/24/2023, 10:19:38 AM

**Comment by afelisatti** [comment]
Hi, @mohanmmm. The Github releases here no longer reflect the status of VS Code. This is because this repo has transitioned to solely an issue tracker. We won't be updating those. Sorry for the confusion and thanks!
